version: "3"

services:
  sqlserver:
    build: ./docker/sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    container_name: sqlserver
    volumes: 
      - mssql-volume:/var/opt/mssql

  webserver:
    build: ./docker/webserver
    container_name: webserver-5.6
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
    ports:
      - "80:80"
      - "443:443"

volumes:
  mssql-volume:

